---
title: "Time Series Inventory Demand Forecasting on MVA data using ARIMA and SARIMA"
author: "Akshitha, Jahnavi, Geetika, Navya Sree"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
# Akshitha Thokala    - 160121771072
# Buggala Jahnavi     - 160121771075
# Guduru Geetika      - 160121771078
# Jamalpur Navya Sree - 160121771079
```

```{r}
#necessary libraries
library(ggplot2)
library(tseries)
library(dplyr)
library(forecast)
library(gam)

#Overview of data
df=read.csv(file.choose())
head(df)
tail(df)
dim(df)
str(df)
summary(df)


##############  PREPROCESSING #############################

#Converting Month to numeric value
months <- c("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")
convert_to_number <- function(month_abbr) {
  month_index <- match(month_abbr, months)
  if (is.na(month_index)) {
    return(NA)
  }
  if (month_index < 10) {
    return(paste0("0", month_index))
  } else {
    return(as.character(month_index))
  }
}

df$Month_Number <- lapply(df$Month, convert_to_number)
df$Month_Number <- unlist(df$Month_Number)
head(df)
str(df)

df<-subset(df,select=-c(Month))
head(df)

#Changing column names
colnames(df)[which(colnames(df) == "Month_Number")] <-"Month"
colnames(df)[which(colnames(df) == "New")] <-"New_Vehicles_Quantity"
colnames(df)[which(colnames(df) == "Used")] <-"Used_Vehicles_Quantity"
head(df)
str(df)

#Finding null values
colnames(df)

sum(is.na(df))

df$Start_of_Month <- as.Date(paste(df$Year, df$Month, "01", sep = "-"))
head(df)
sum(is.na(df$Start_of_Month))

#converting to date class
df$Start_of_Month<-as.Date(df$Start_of_Month)
typeof(df$Start_of_Month)
class(df$Start_of_Month)

str(df)

summary(df)


######################## Data visualization #################################


#Combined Analysis of new and used vehicles
new_df<-data.frame(Quantity_sold=c(df$New_Vehicles_Quantity+df$Used_Vehicles_Quantity),
                   Total.Sales=c(df$Total.Sales.New+df$Total.Sales.Used),
                   Start_of_Month=c(df$Start_of_Month))
new_df$Month<-df$Month
new_df$Year<-df$Year
head(new_df)
summary(new_df)
dim(new_df)

#Line Chart
ggplot(new_df, aes(x = Month, y = Quantity_sold)) +
  geom_line() +
  labs(title = "Monthly Sales Over all Years", x = "Month", y = "Sales")

#Bar chart
ggplot(new_df, aes(x = Month, y = Quantity_sold)) +
  geom_bar(stat = "identity") +
  labs(title = "Monthly Sales Over all Years", x = "Month", y = "Sales")

#Box plot
ggplot(new_df, aes(x = Month, y = Quantity_sold)) +
  geom_boxplot() +
  labs(title = "Distribution of Monthly Sales", x = "Month", y = "Sales")

#Cumulative sales
new_df$Cumulative_Sales <- cumsum(as.numeric(new_df$Total.Sales))

# Print the updated data frame
head(new_df)

#Area chart
ggplot(new_df, aes(x = Year, y = Cumulative_Sales,fill=Year)) +
  geom_area() +
  labs(title = "Cumulative Sales Over a Year", x = "Month", y = "Cumulative Sales")

############################# Data modelling #####################################

# ----------------------------- NEW VEHICLES -------------------------------------

head(df)
new_v = data.frame(df$Start_of_Month,df$New_Vehicles_Quantity)
head(new_v)

#To build arima and sarima model required attributes

new_v <- new_v %>%
  mutate(Sales_First_Difference = df.New_Vehicles_Quantity - lag(df.New_Vehicles_Quantity))
head(new_v)

new_v <- new_v %>%
  mutate(Seasonal_First_Difference = df.New_Vehicles_Quantity - lag(df.New_Vehicles_Quantity, 12))
head(new_v)

#seasonal first difference 
new_v$Seasonal_First_Difference <- c(rep(NA, 12), new_v$df.New_Vehicles_Quantity[13:nrow(new_v)] - new_v$df.New_Vehicles_Quantity[1:(nrow(new_v) - 12)])
print(new_v)

#seasonal first difference plot
new_v$Seasonal_First_Difference <- c(rep(NA, 12), new_v$df.New_Vehicles_Quantity[13:nrow(df)] - new_v$df.New_Vehicles_Quantity[1:(nrow(new_v) - 12)])
plot(new_v$Seasonal_First_Difference, type = "l", xlab = "Time", ylab = "Seasonal First Difference", main = "Seasonal First Difference Plot")

## Impute missing values with mean
new_v$df.New_Vehicles_Quantity[is.na(new_v$df.New_Vehicles_Quantity)] <- mean(df$df.New_Vehicles_Quantity, na.rm = TRUE) 

## Convert data to time series object
ts_data <- ts(new_v$df.New_Vehicles_Quantity)

# Replace missing values with the mean of existing values
new_v$Seasonal_First_Difference[is.na(new_v$Seasonal_First_Difference)] <- mean(new_v$Seasonal_First_Difference, na.rm = TRUE)


# Plot the autocorrelation and partial autocorrelation
par(mfrow = c(2, 1))  # Set up a 2x1 grid of plots
acf(new_v$Seasonal_First_Difference, lag.max = 40, main = "Autocorrelation Plot")
pacf(new_v$Seasonal_First_Difference, lag.max = 40, main = "Partial Autocorrelation Plot")

new_v$df.New_Vehicles_Quantity[is.na(new_v$df.New_Vehicles_Quantity)] <- mean(df$df.New_Vehicles_Quantity, na.rm = TRUE)

#Training and testing data
tail(new_v,20)
train_df<-new_v[1:252,]
tail(train_df,1)

test_df<-new_v[253:266,]
print(test_df)


#----------------------------------------------ARIMA----------------------------------------------------------------
model <- Arima(train_df$df.New_Vehicles_Quantity, order = c(3, 1, 2))
# Make forecasts
forecast_values1 <- forecast(model, h = 14, dynamic = TRUE)
forecast_values1[4]
predicted_values1<-c(22508.66, 22306.12, 22831.39, 22359.26, 22623.72, 22558.46, 22505.64, 22593.01, 22523.39, 22557.77, 22553.13,
                     22542.12, 22556.15, 22546.15)
accuracy(test_df$df.New_Vehicles_Quantity,predicted_values1)
# Plot the forecasts along with the actual sales data
plot(forecast_values1, main = "Sales Forecast from Arima")
lines(df$New_Vehicles_Quantity, col = "red")



#----------------------------------------------SARIMA-------------------------------------------------------------------
model2 <- arima(train_df$df.New_Vehicles_Quantity, order = c(2, 1, 3), seasonal = list(order = c(2, 1, 3), period = 12))

# Print the model summary
summary(model2)

forecast_values <- forecast(model2, h = 14, dynamic = TRUE)
# Accuracy of Sarima

predicted_values<-c(21657.80, 18706.90, 25264.67, 26414.12, 26617.36, 25797.82, 24431.42, 23965.55, 23238.43, 22459.76, 19258.11,
                    20899.36, 21610.99, 17864.31)

accuracy(test_df$df.New_Vehicles_Quantity,predicted_values)
# Plot the forecasts along with the actual sales data
plot(forecast_values, main = "Sales Forecast from Sarima")
lines(df$New_Vehicles_Quantity, col = "red")

# Set up the plot area
par(mar = c(5, 5, 4, 2) + 0.1)  # Adjust margins to provide space for labels

#----------------------- Forecast values-----------------------------------------

future_dates <- seq(as.Date("2024-03-01"), by = "month", length.out = 204)
future_df <- data.frame(Date = future_dates)
future_df$forecast <- forecast(model2, h = 204)$mean

head(future_df)

plot(future_df$Date, future_df$forecast, type = "l", xlab = "Date", ylab = "Forecast", main = "Forecasted Sales", xlim = range(future_df$Date), xaxt = "n", col = "red", lwd = 2)
axis.Date(1, at = future_df$Date, labels = format(future_df$Date, "%Y-%m"), cex.axis = 0.7, las = 2)
grid(col = "lightgray", lwd = 0.5)
legend("topright", legend = "Forecast", col = "red", lty = 1, lwd = 2, cex = 0.8)

#------------------- GAM model --------------------------------

new_vehicles<-subset(df,select=c(New_Vehicles_Quantity, Total.Sales.New))

head(new_vehicles)
train_df_v<-new_vehicles[1:252,]
test_df_v<-new_vehicles[253:266,]
gam_model <- gam(Total.Sales.New ~ s(New_Vehicles_Quantity), data = train_df_v)
summary(gam_model)


predictions <- predict(gam_model, newdata = test_df_v, type = "response")
accuracy(predictions,test_df_v$New_Vehicles_Quantity)

#------------------------------------------------------------------------------

names(future_df)[names(future_df) == "forecast"] <- "New_Vehicles_Quantity"

predictions_f <- predict(gam_model, newdata = future_df, type = "response")

future_df$Total.Amount<-predictions_f

head(future_df)
```
